### ISSUE TITLE
for help: how to install in linux(ubuntu22) system

### ISSUE THREAD

**Issue by RvMe** [Leonm99/Stable-Diffusion-Video2Video#1]
i find it can't work in Linux system (Ubuntu 22)(maybe my install process wrong),although stable diffusion can work

i follow your tip to install [FFMPEG] , put vid2vid.py in script,start sd,but i can't find video2video in img2img

then i try to run vid2vid.py,but error:ImportError: cannot import name 'opts' from partially initialized module 'modules.shared' (most likely due to a circular import) (/home/hr/stable-diffusion-webui/modules/shared.py)

so maybe if you can teach me how to install your py in linux system?
thank you very much!

**Comment by RvMe** [comment]
oh,i find it in the script button!
and in Ubuntu(Linux),[vid2vid.py] need to change   '\\'  ----->  '/'   insure your touch that dictionary
very thx author's py!
love u!

**Comment by Leonm99** [comment]
Hey, glad you fixed it. i knew about that issue actually. i made the script when i used windows only. but luckily now im using linux as well so i will fix that in the coming days and maybe improve the script a bit. thanks for mentioning it!

**Comment by RvMe** [comment]
Wow! look forward your script !!
and here maybe you feel interest in:
i wanna make video like this: 

&nbsp;https://www.bilibili.com/video/BV1mg411h7P7/?share_source=copy_web&amp;vd_source=821c047ff69a5077723f9db653622110
and input video is this:
&nbsp;https://www.bilibili.com/video/BV1kb4y1m7e7/?share_source=copy_web&amp;vd_source=821c047ff69a5077723f9db653622110
i keep trying ,but result not good.&nbsp; XD
anyhow, best wishes! and thanks for your mail !~



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月9日(星期三) 凌晨0:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Leonm99/Stable-Diffusion-Video2Video] for help: how to install in linux(ubuntu22) system (Issue #1)





 
Hey, glad you fixed it. i knew about that issue actually. i made the script when i used windows only. but luckily now im using linux as well so i will fix that in the coming days and maybe improve the script a bit. thanks for mentioning it!
