### ISSUE TITLE
how use script

### ISSUE THREAD

**Issue by bropines** [Leonm99/Stable-Diffusion-Video2Video#10]
AttributeError: 'NoneType' object has no attribute 'convert'
I'm trying to run it but it doesn't give anything
https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py
I use this script

**Comment by airborne-commando** [comment]
Same issue here, using Linux.

**Comment by qpalfj1234** [comment]
You need put a image at first
