### ISSUE TITLE
"slash" in the directory name

### ISSUE THREAD

**Issue by ducktaperules** [Leonm99/Stable-Diffusion-Video2Video#3]
# Define a subfolder in our folder to seperate different prompts
        sub_folder = root_path + file_name + "slash"
        
        i think this "slash" is wrong as it creates directory names with the word slash at the end. 
        
        should be without the quotes?

**Comment by Leonm99** [comment]
Oh yeah my bad. i already fixed that but i havent had time to push it out haha. thanks for your help.
