### ISSUE TITLE
can't find saved files

### ISSUE THREAD

**Issue by 4lt3r3go** [Leonm99/Stable-Diffusion-Video2Video#7]
I looking everywere for the genrated video and the frames but i'm unable to find them
any clue?

**Comment by RvMe** [comment]
![图片](https://user-images.githubusercontent.com/56872189/207868291-5cd602eb-cc7f-4704-8d75-f3566aa78ff8.png)
if u don't write any word in prompt, u will can't find generated video~

**Comment by 4lt3r3go** [comment]
sure i wrote there and i saw everything working. when finished i dont have any video or saved pngs

**Comment by Leonm99** [comment]
it should be under \outputs\vid2vid\[Beginning of prompt]\
what operating system are you using, and are there any errors?

**Comment by Leonm99** [comment]
check this out: https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py

im discontinuing my version of vid2vid since this person seems to have done it better/improved on it. hope it will work well for you!
