### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified 

### ISSUE THREAD

**Issue by 3090goBRRR** [Leonm99/Stable-Diffusion-Video2Video#9]
FileNotFoundError: [WinError 2] The system cannot find the file specified
Time taken: 0.01sTorch active/reserved: 2070/2082 MiB, Sys VRAM: 3328/24576 MiB (13.54%)

The vid2vid is not seeing the file? Its an mp4 on the desktop. Am I doing something wrong here?

**Comment by Leonm99** [comment]
check this out: https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py

im discontinuing my version of vid2vid since this person seems to have done it better/improved on it. hope it will work well for you!
